title: "Urban Data Science Workshop"
title: "Urban Data Science Workshop"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false
url: https://heikalab.github.io/urbandatascience/
